### ISSUE TITLE
Defect: register_alloc_comp_{1,2,3} tests fail on Fedora

### ISSUE THREAD

**Issue by susilehtola** [sourceryinstitute/OpenCoarrays#710]
The register_alloc_comp_{1,2,3} tests fail on Fedora:
```
 7/78 Test  #7: register_alloc_comp_1 .................***Failed  Required regular expression not found. Regex=[Test passed.
]  1.49 sec
[buildvm-x86-07:1262981] *** An error occurred in MPI_Win_detach
[buildvm-x86-07:1262981] *** reported by process [1058275329,1]
[buildvm-x86-07:1262981] *** on win rdma window 5
[buildvm-x86-07:1262981] *** MPI_ERR_UNKNOWN: unknown error
[buildvm-x86-07:1262981] *** MPI_ERRORS_ARE_FATAL (processes in this win will now abort,
[buildvm-x86-07:1262981] ***    and potentially your MPI job)
[buildvm-x86-07.iad2.fedoraproject.org:1262976] 1 more process has sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[buildvm-x86-07.iad2.fedoraproject.org:1262976] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Error: Command:
   `/usr/lib64/openmpi/bin/mpiexec -n 2 --hostfile /builddir/build/BUILD/OpenCoarrays-2.8.0/openmpi/hostfile --allow-run-as-root /builddir/build/BUILD/OpenCoarrays-2.8.0/openmpi/bin/OpenCoarrays-2.8.0-tests/register_alloc_comp_1`
failed to run.
      Start  8: register_alloc_comp_2
 8/78 Test  #8: register_alloc_comp_2 .................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.97 sec
[buildvm-x86-07:1262999] *** An error occurred in MPI_Win_detach
[buildvm-x86-07:1262999] *** reported by process [1057357825,1]
[buildvm-x86-07:1262999] *** on win rdma window 5
[buildvm-x86-07:1262999] *** MPI_ERR_UNKNOWN: unknown error
[buildvm-x86-07:1262999] *** MPI_ERRORS_ARE_FATAL (processes in this win will now abort,
[buildvm-x86-07:1262999] ***    and potentially your MPI job)
[buildvm-x86-07.iad2.fedoraproject.org:1262994] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Backtrace for this error:
#0  0x7efe95c97d74 in ???
#1  0x7efe95c96f75 in ???
#2  0x7efe95916b7f in ???
#3  0x7efe8f628220 in ???
[buildvm-x86-07.iad2.fedoraproject.org:1262994] 1 more process has sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[buildvm-x86-07.iad2.fedoraproject.org:1262994] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Error: Command:
   `/usr/lib64/openmpi/bin/mpiexec -n 2 --hostfile /builddir/build/BUILD/OpenCoarrays-2.8.0/openmpi/hostfile --allow-run-as-root /builddir/build/BUILD/OpenCoarrays-2.8.0/openmpi/bin/OpenCoarrays-2.8.0-tests/register_alloc_comp_2`
failed to run.
      Start  9: register_alloc_comp_3
 9/78 Test  #9: register_alloc_comp_3 .................***Failed  Required regular expression not found. Regex=[Test passed.
]  0.93 sec
[buildvm-x86-07:1263021] *** An error occurred in MPI_Win_detach
[buildvm-x86-07:1263021] *** reported by process [1060896769,1]
[buildvm-x86-07:1263021] *** on win rdma window 5
[buildvm-x86-07:1263021] *** MPI_ERR_UNKNOWN: unknown error
[buildvm-x86-07:1263021] *** MPI_ERRORS_ARE_FATAL (processes in this win will now abort,
[buildvm-x86-07:1263021] ***    and potentially your MPI job)
[buildvm-x86-07.iad2.fedoraproject.org:1263016] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Backtrace for this error:
#0  0x7fb1c0bcfd74 in ???
#1  0x7fb1c0bcef75 in ???
#2  0x7fb1c084eb7f in ???
#3  0x7fb1be56c220 in ???
[buildvm-x86-07.iad2.fedoraproject.org:1263016] 1 more process has sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[buildvm-x86-07.iad2.fedoraproject.org:1263016] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Error: Command:
   `/usr/lib64/openmpi/bin/mpiexec -n 2 --hostfile /builddir/build/BUILD/OpenCoarrays-2.8.0/openmpi/hostfile --allow-run-as-root /builddir/build/BUILD/OpenCoarrays-2.8.0/openmpi/bin/OpenCoarrays-2.8.0-tests/register_alloc_comp_3`
failed to run.
```

This is on x86_64, the other platforms also have the same issues. Full log files for the x86_64 build at

[root.log](https://github.com/sourceryinstitute/OpenCoarrays/files/4896531/root.log)
[build.log](https://github.com/sourceryinstitute/OpenCoarrays/files/4896532/build.log)

**Comment by susilehtola** [comment]
Same failures also exist in OpenCoarrays-2.9.0.

**Comment by susilehtola** [comment]
OpenCoarrays has been retired from Fedora since it hasn't built successfully in over a half year.
